# Some constant variable about real court
SINGLE_LINE_WIDTH = 8.23
DOUBLE_LINE_WIDTH = 10.97
HALF_COURT_LINE_HEIGHT = 11.88
SERVICE_LINE_WIDTH = 6.4
DOUBLE_ALLY_DIFFERENCE = 1.37
NO_MANS_LAND_HEIGHT = 5.48

# Some constant variable about real player
PLAYER_1_HEIGHT_METERS = 1.88 # Djokovic
PLAYER_2_HEIGHT_METERS = 1.91 # Sonega